package com.dev.quickcart.ui.theme

import androidx.compose.ui.graphics.Color


data class AppColors(

    val primary: Color,
    val primaryShades: Color,
    val onPrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val teal: Color,
    val error: Color,
    val successColor: Color,
    val onError: Color,
    val outline: Color,
    val background: Color,
    val onBackground: Color,
    val textColorLight: Color,
    val textColorMedium: Color,
    val textColorDark: Color,
    val inputBackground: Color,
    val cardBackgroundColor: Color,
    val lightGray: Color,
    val white: Color,
    val googleButtonColor: Color,
    val otpCard: Color,
    val black: Color,
    val borderGray: Color,
    val minusGray: Color,
    val darkGreen: Color = Color(0xFF005418),
    val cardShadow: Color,
    val billCardBg: Color,
    val billCardText: Color,
    val billCardIcon: Color,
    val divider: Color,
    val primaryText: Color,
    val secondaryText: Color,
    val brandText: Color,
    val standardBorder: Color,
    val accentBorder: Color,
    val address_bg: Color,
    val address_text: Color,
    val back_bg: Color = Color(0xFF40c79a),
    val topbar_bg: Color = Color(0xFF12b898),
    val edit_bg: Color = Color(0xFFecfdf5),
    val delete_bg: Color = Color(0xFFfef2f2),

    )


val customAppColorsLight = AppColors(
    cardShadow = Color(0x333A4A5A),
    primary = Color(0xFF22c55e),
    primaryShades = Color(0xFFf0fdf4),
    onPrimary = Color(0xFFFAFAFA),
    secondary = Color(0xFFFF324B),
    onSecondary = Color(0xFFFFFFFF),
    teal = Color(0xFF14b8a6),
    error = Color(0xFFef4444),
    successColor = Color(0xFF16a34a),
    onError = Color(0xFFFFFFFF),
    outline = Color(0xFF74777F),
    background = Color(0xFFf9fafb),
    onBackground = Color(0xFF001F25),
    textColorLight = Color(0xFF979899),
    textColorMedium = Color(0xFF2F2F2F),
    textColorDark = Color(0xFF06161C),
    inputBackground = Color(0xFFf9fafb),
    cardBackgroundColor = Color(0xFFf3f4f6),
    lightGray = Color(0xFF979899),
    white = Color(0xFF06161C),
    googleButtonColor = Color(0xFF5383EC),
    otpCard = Color(0xFFF0F1F2),
    black = Color(0xFF0D0D0D),
    borderGray = Color(0xFF1A2525),
    minusGray = Color(0xFFB3B3B3),
    darkGreen = Color(0xFF005418),
    billCardBg = Color(0xFFF5F8FF),
    billCardText = Color(0xFF333333),
    billCardIcon = Color(0xFF4CAF50),
    divider = Color(0xFFE0E0E0),
    primaryText = Color(0xFF111827),
    secondaryText = Color(0xFF4B5563),
    brandText = Color(0xFF22c55e),
    standardBorder = Color(0xFFe5e7eb),
    accentBorder = Color(0xFFbbf7d0),
    address_bg = Color(0xFFecfdf5),
    address_text = Color(0xFFecfdf5)
)



val customAppColorsDark = AppColors(
    cardShadow = Color(0x4D8090A0),
    primary = Color(0xFF4ade80),
    primaryShades = Color(0xFF15803d),
    onPrimary = Color(0xFFFAFAFA),
    secondary = Color(0xFFFF324B),
    onSecondary = Color(0xFF3F2E00),
    teal = Color(0xFF2dd4bf),
    error = Color(0xFFf87171),
    successColor = Color(0xFF4ade80),
    onError = Color(0xFF690005),
    outline = Color(0xFF8D9199),
    background = Color(0xFF111827),
    onBackground = Color(0xFFA6EEFF),
    textColorLight = Color(0xFF828282),
    textColorMedium = Color(0xFFCDCDCD),
    textColorDark = Color(0xFFFFFFFF),
    inputBackground = Color(0xFF374151),
    cardBackgroundColor = Color(0xFF1f2937),
    lightGray = Color(0xFF617986),
    white = Color(0xFFFAFAFA),
    googleButtonColor = Color(0xFF5383EC),
    otpCard = Color(0xFF1A3848),
    black = Color(0xFFFAF9F6),
    borderGray = Color(0xFF2F2F2F),
    minusGray = Color(0xFFF5FEFD),
    darkGreen = Color(0xFF005418),
    billCardBg = Color(0xFF232733),
    billCardText = Color(0xFFE0E0E0),
    billCardIcon = Color(0xFF66BB6A),
    divider = Color(0xFF3A3F4B),
    primaryText = Color(0xFFE5E7EB),
    secondaryText = Color(0xFF6B7280),
    brandText = Color(0xFF4ade80),
    standardBorder = Color(0xFF374151),
    accentBorder = Color(0xFF15803d),
    address_bg = Color(0xFFecfdf5),
    address_text = Color(0xFF047857)



)